services:
  era5:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .cdsapirc:/root/.cdsapirc
      - ./service-account.json:/root/service-account.json
      - ./in:/in
      - ./out:/out
      - ./src:/src
    environment:
      # TOOL_RUN: download_era5_series
      TOOL_RUN: download_cmip6_series
      
      # CHANGE this bucket name, if you change the service account to your account
      BUCKET: vfw_ee_export
    command: ["echo", "Run the tool like: docker compose run --rm era5 python run.py"]